name: vault4s
baseurl: /vault4s
description: Vault Client Library For Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 5.0.1-SNAPSHOT
org: Jack Henry & Associates, Inc.®
markdown: kramdown
